title : Hello, My name is Kiuk Paeng. I am supply chain professonial with strong passion in data science. <br>
I want to sovle supply chain problem with data science.
#logo: /assets/img/headshot_circle.png
#description : text below image
show_downloads : true
theme : jekyll-theme-minimal
